name: mergable and merge_state

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was opened,reopened,edited " 
